### ISSUE TITLE
Requests for extra function

### ISSUE THREAD

**Issue by SiDronee** [Fear-and-Terror-EU-Programming-Team/fear-and-terror-squad-tracker-bot#1]
Is it possible to get an extra function? 
You see current map, but would be nice to also see 

Next:
{map} 

![image](https://user-images.githubusercontent.com/59602143/80800793-af4d4780-8baa-11ea-8be2-1496d477a989.png)

**Comment by w4rum** [comment]
Unfortunately, the Squad servers do not publish the follow-up map via the A2S protocol. Here's an excerpt of what the responses from the squad server look like:
https://pastebin.com/wMXPbXzD

Note that the `A2S_INFO` response lists the current map in `map` (line 6). The info in the `A2S_INFO` response is what you would see in the official Steam server browser. The reply to `A2S_RULES` is custom-made by OWI. But as you can see, they left out the follow-up map.

It *might* be possible to extract the follow-up map via an RCON connection but adding RCON access to the bot would increase the complexity more than it's worth. Also, accessing RCON would require the bot to know RCON credentials for the servers.

So unless there is a simpler way to query the follow-up map, I don't think adding that feature is worth the effort.
